import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FeatureFlowProvider } from "featureflow-react-sdk";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <FeatureFlowProvider apiKey="ff_live_356c213e80a0792e7330b5d5c003fb00" userContext={{ id: '9d784224-a8f5-4d92-aa32-a9d143a28538', plan: 'pro' }}>

        {children}
        </FeatureFlowProvider>
        </body>
    </html>
  );
}
